# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gaussian distribution random number generater
#' @description A Gaussian distribution random number generater using Rcpp
#' @param mu the mean of Gaussian distribution
#' @param sigma the standard deviation of Gaussian distribution
#' @return a random number form N(mu,sigma^2)
#' @useDynLib StatComp20056
#' @examples
#' \dontrun{
#' Guassian(0,1)
#' }
#' @export
Gaussian <- function(mu, sigma) {
    .Call('_StatComp20056_Gaussian', PACKAGE = 'StatComp20056', mu, sigma)
}

#' @title Laplace density function
#' @description Standard Laplace distribution density  using Rcpp
#' @param x a real number
#' @return the density at number x
#' @useDynLib StatComp20056
#' @examples
#' \dontrun{
#' lap(0)
#' }
#' @export
lap <- function(x) {
    .Call('_StatComp20056_lap', PACKAGE = 'StatComp20056', x)
}

#' @title Random Walk Metropolis Sampler
#' @description  Generate  a sample that obeys standard Laplace distribution by Random walk Metropolis, which uses proposal distribution normal (X_t,sigma^2). The data generation process records the acceptance rate.
#' @param n the size of sample
#' @param sigma the standard deviation of proposal Gaussian distribution
#' @param x0 the initial value of random walk
#' @return A sample that obeys standard Laplace distribution and acceptance rates.
#' @useDynLib StatComp20056
#' @examples
#' \dontrun{
#' a1<-as.numeric(metro(4000,1,10))
#' a1[1]
#' }
#' @export
metro <- function(n, sigma, x0) {
    .Call('_StatComp20056_metro', PACKAGE = 'StatComp20056', n, sigma, x0)
}

